FROM python

RUN apt update && apt install -y nano cron && pip install requests

RUN touch /var/spool/cron/crontabs/root && \
    crontab /var/spool/cron/crontabs/root && \
    echo "* * * * * /home/script.sh >> /home/backup.log" >> /var/spool/cron/crontabs/root