FROM python

COPY ./docker_quality_file/crontab /var/spool/cron/crontabs/root
RUN apt update && apt install -y nano cron mongo-tools && pip install requests pytz datetime
RUN touch /var/spool/cron/crontabs/root && crontab /var/spool/cron/crontabs/root
